name: Docker CI

on:
  push:
    branches:
      - main
      - feature*
  pull_request:
    branches:
      - main
      - feature*

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      name: Check out the repository code
      
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
      
    - name: Run Docker environment test script
      run: |
        chmod +x ./ci/docker_tests.sh
        ./ci/docker_tests.sh

    # Add the diagnostic steps here
    - name: Check Docker and Container State
      run: |
        docker ps -a
        docker images
        docker logs my_jupyter_cadquery_test || true # Use '|| true' to ensure the workflow continues even if this command fails
