name: Python application test with Mamba
  2
  3 on:
  4   push:
  5     branches: [
  6                 main,
  7                 develop,
  8                 feature-github*
  9               ]
 10   pull_request:
 11     branches: [
 12                 main,
 13                 develop
 14               ]
 15
 16 jobs:
 17   build:
 18
 19     runs-on: ubuntu-latest
 20
 21     steps:
 22     - uses: actions/checkout@v2
 23       with:
 24         fetch-depth: 0
 25
 26     - name: Setup Mamba
 27       uses: conda-incubator/setup-miniconda@v2
 28       with:
 29         auto-update-conda: true
